// <auto-generated />
namespace Bootstrap.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_rolePermissiontable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_rolePermissiontable));
        
        string IMigrationMetadata.Id
        {
            get { return "201805140341141_update_rolePermissiontable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
