// <auto-generated />
namespace Bootstrap.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_menutable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_menutable));
        
        string IMigrationMetadata.Id
        {
            get { return "201805120141344_remove_menutable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
