// <auto-generated />
namespace Bootstrap.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class reloadtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reloadtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201805120310384_reloadtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
